/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package supermarket.edu.ijse.View;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author dinuka
 */
public class MainCustomerManagePanelView extends javax.swing.JPanel {

    /**
     * Creates new form CustomerPanelView
     */
    public MainCustomerManagePanelView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnAddCust = new javax.swing.JButton();
        btnSearchCust = new javax.swing.JButton();
        btnUpdateCust = new javax.swing.JButton();
        btnDeleteCuts = new javax.swing.JButton();
        panel = new javax.swing.JPanel();

        jPanel1.setBackground(new java.awt.Color(127, 199, 217));

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(15, 16, 53));
        jLabel1.setText("   Manage Customer");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        btnAddCust.setBackground(new java.awt.Color(106, 156, 137));
        btnAddCust.setForeground(new java.awt.Color(255, 255, 255));
        btnAddCust.setText("Add Customer");
        btnAddCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCustActionPerformed(evt);
            }
        });

        btnSearchCust.setBackground(new java.awt.Color(106, 156, 137));
        btnSearchCust.setForeground(new java.awt.Color(255, 255, 255));
        btnSearchCust.setText("Search Customer");
        btnSearchCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchCustActionPerformed(evt);
            }
        });

        btnUpdateCust.setBackground(new java.awt.Color(106, 156, 137));
        btnUpdateCust.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateCust.setText("Update Customer");
        btnUpdateCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateCustActionPerformed(evt);
            }
        });

        btnDeleteCuts.setBackground(new java.awt.Color(106, 156, 137));
        btnDeleteCuts.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteCuts.setText("Delete Customer");
        btnDeleteCuts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCutsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(btnAddCust)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearchCust)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdateCust)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeleteCuts)
                .addContainerGap(95, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddCust)
                    .addComponent(btnSearchCust)
                    .addComponent(btnUpdateCust)
                    .addComponent(btnDeleteCuts))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 451, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCustActionPerformed
        try {
            addCustomerPanel();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainCustomerManagePanelView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MainCustomerManagePanelView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAddCustActionPerformed

    private void btnSearchCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchCustActionPerformed
        try {
            searchCustPanel();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainCustomerManagePanelView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MainCustomerManagePanelView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSearchCustActionPerformed

    private void btnUpdateCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateCustActionPerformed
        try {
            updateCustPanel();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainCustomerManagePanelView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MainCustomerManagePanelView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnUpdateCustActionPerformed

    private void btnDeleteCutsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCutsActionPerformed
        try {
            deleteCustomerPanel();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainCustomerManagePanelView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MainCustomerManagePanelView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDeleteCutsActionPerformed

    private void addCustomerPanel() throws ClassNotFoundException, SQLException{
        panel.removeAll();
        AddCustomerPanelView addCustpanel = new AddCustomerPanelView();
        addCustpanel.setSize(panel.getWidth(), panel.getHeight());
        panel.add(addCustpanel);
        panel.repaint();
        panel.revalidate();
    }
    
    private void deleteCustomerPanel() throws ClassNotFoundException, SQLException{
        panel.removeAll();
        DeleteCustomerPanelView deleteCust = new DeleteCustomerPanelView();
        deleteCust.setSize(panel.getWidth(), panel.getHeight());
        panel.add(deleteCust);
        panel.repaint();
        panel.revalidate();
    }
    
    private void updateCustPanel() throws ClassNotFoundException, SQLException{
        panel.removeAll();
        UpdateCustomerView updateCust = new UpdateCustomerView();
        updateCust.setSize(panel.getWidth(), panel.getHeight());
        panel.add(updateCust);
        panel.repaint();
        panel.revalidate();
    }
    
    
     private void searchCustPanel() throws ClassNotFoundException, SQLException{
        panel.removeAll();
        SearchCustomerPanelView searchCust = new SearchCustomerPanelView();
        searchCust.setSize(panel.getWidth(), panel.getHeight());
        panel.add(searchCust);
        panel.repaint();
        panel.revalidate();
    }
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCust;
    private javax.swing.JButton btnDeleteCuts;
    private javax.swing.JButton btnSearchCust;
    private javax.swing.JButton btnUpdateCust;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
